# Generated by Django 4.2.5 on 2023-11-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='phone',
            new_name='car_no',
        ),
    ]
