# Generated by Django 4.2.5 on 2023-11-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_alter_slots_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='1234', max_length=200)),
                ('per_hour', models.IntegerField(default=50)),
                ('per_hour_vip', models.IntegerField(default=80)),
            ],
        ),
    ]
