# Generated by Django 4.2.5 on 2023-11-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_cheakout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheakout',
            name='total',
            field=models.FloatField(),
        ),
    ]
