# Generated by Django 4.2.5 on 2023-11-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
